### ISSUE TITLE
Package dependency problem?

### ISSUE THREAD

**Issue by jackfirth** [srfoster/game-engine#1]
Hi, I wrote the `jack-posn` package and saw your IRC message about installation issues. Did you happen to find a fix? Cool project by the way!

**Comment by srfoster** [comment]
Wow, thanks for following up.

I didn't find a fix other than to install jack-posn separately before installing game-engine.  This works for me, but I'd be curious to know why it's not installing automatically.

I was looking at your repo and I didn't see anything weird.  Maybe I'm referencing the dependency the wrong way?

**Comment by jackfirth** [comment]
Looking closer, I think this is because DrRacket's package installation UI is a little confusing. If you click the "show details" button in the DrRacket package installer window there's a drop-down labeled "Dependencies Mode". On my 6.11 installation this was set to "Default" which apparently means "fail if there are dependencies to install". Setting this to "Auto" which installs any missing dependency packages (which might be a more sensible default) fixed the problem.

**Comment by srfoster** [comment]
Cool!  Thanks for looking into that.  That's a great fix.

I guess I'm still a bit puzzled, though, because I have another package (spaceship-game-demo) which lists this package (game-engine) as a dependency.  I don't get the same failure, though.  It installs both packages just fine when I tell DrRacket to install spaceship-game-demo.
